import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo, Ravi_Prakash, Inknut_Antiqua, Aboreto, Poppins ,Fruktur } from "next/font/google";

import "./globals.css";
import Nextauthprovider from "./provider/nextauthprovider";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-cairo",
});

const brick3D = Fruktur({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-fruktur",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const aboreto = Aboreto({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-aboreto",
});

const inknutAntiqua = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inknut-antiqua",
});

const raviPrakash = Ravi_Prakash({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ravi-prakash",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Egyptus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`flex flex-col h-screen overflow-y-auto ${brick3D.variable} ${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${aboreto.variable} ${cairo.variable} ${raviPrakash.variable} ${inknutAntiqua.variable} antialiased`}
      >
        <Nextauthprovider>
          <Header />
          <main className="flex-grow flex flex-col">{children}</main>
          <Footer />
        </Nextauthprovider>
      </body>
    </html>
  );
}